export const routeConstants = {
  HOME: "home",
  APP_SELECT: "app-select",
  KEXY: {
    LOGIN: "kexy-login",
    REGISTER: "kexy-register",
    LOGIN_DICISION: "kexy-login-decision",
    FORGET_PASSWORD: "kexy-forget-password",
    PASSWORD_RESET: "kexy-password-reset",
    EMAIL_CONFIRMATION: "kexy-email-confirmation",
    EMAIL_VERIFICATION: "kexy-email-verification",
    ADD_NEW_PRODUCT: "kexy-add-new-product",
    JOIN_MARKETPLACED: "kexy-join-marketplace",
    TERMS_AND_CONDITION: "kexy-terms-conditions",
    WELCOME: "kexy-welcome",
    MARKETPLACE_TYPE: "kexy-marketplace-type",
    DISTRIBUTOR_SELECT_TYPE: "kexy-distributor-select-type",
    RESTAURANT_TYPE: "kexy-restaurant-type",
    SUPPLIER_SELECT_TYPE: "kexy-supplier-select-type",
    RESTAURANT_CREATE: "kexy-restaurant-create",
    INVITE_RESTAURANT_EMPLOYEE: "kexy-invite-restaurant-employee",
    DISTRIBUTOR_CREATE: "kexy-distributor-create",
    DISTRIBUTOR_SETUP_RESTAURANT_BAR: "kexy-distributor-setup-restaurant-bar",
    INVITE_DISTRIBUTOR_EMPLOYEE: "kexy-invite-distributor-employee",
    SUPPLIER_CREATE: "kexy-supplier-create",
    SUPPLIER_INVITE_EMPLOYEE: "kexy-supplier-invite-employee",
    TUTORIAL: "kexy-restaurant-tutorial",
    RESTAURANT_TABS: "kexy-restaurant-tabs",
    RESTAURANT_DASHBOARD: "kexy-restaurant-dashboard",
    EDIT_PROFILE: "kexy-restaurant-edit-profile",
    PLACE_ORDER: "kexy-restaurant-place-order",
    CONTACTS: "kexy-restaurant-contacts",
    ALL_CONTACTS: "kexy-restaurant-all-contacts",
    EDIT_RESTAURANT: "kexy-edit-restaurant",
    INVITE_PEOPLE: "kexy-invite-people",
    SETTINGS: "kexy-settings",
    REP_DELIVERY_METHOD: "kexy-rep-delivery-method",
    JOIN_REQUEST_LIST: "kexy-join-request-list",
    EDIT_DISTRIBUTOR: "kexy-edit-distributor",
    DISTRIBUTOR_DASHBOARD: "kexy-distributor-dashboard",
    MY_RESTAURANTS: "kexy-my-restaurants",
    
  },
};
